name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubunt-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: sudo apt install wget
      - run: wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
      - run: sudo apt install ./chrome-remote-dekstop_current_amd64.deb
      - run: DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AX4XfWg-HlRZ45rNfUHrvz-TtoUxWJAVXCnfeUZDm5kBKgNWwQFKpASBp-m4-b2IWjV3Tw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
